(*########## CONTENTS PLAN ##########
- RE-INTRODUCE THAT PROPOSITIONS DESCRIBES RESOURCES
- IN IRIS, USER CAN DEFINE THEIR OWN NOTION (resource_algebra.v)
- A BASIC NOTION IS THAT OF POINTS-TO PREDICATES (resource for heaps)
- EXAMPLES
- EXCLUSIVITY
- EXAMPLES
- HOARE TRIPLES FOR HEAPLANG HEAP INSTRUCTIONS (STORE, READ, CAS)
#####################################*)
