(*########## CONTENTS PLAN ##########
- INTRODUCE WEAKEST-PRECONDITIONS
  + EXAMPLES WITH BASIC ARITHMETIC
- INTRODUCE HOARE-TRIPLES
  + EXAMPLES
  + RELATIONSHIP TO WP
  + CONVENTION: HT FOR SPECS, WP FOR PROOFS
- POSSIBLY MERGE SPECIFICATIONS AND RESOURCES
  + THEN HAVE EXAMPLES WITH POINTS-TO PREDICATE
#####################################*)
